import { useState } from 'react';
import { usePosts } from '../context/PostContext';

export default function Sidebar() {
  const { posts, scheduleInsight } = usePosts();
  const [activeStatus, setActiveStatus] = useState(null);
  const upcoming = [...posts].filter((post) => new Date(post.start) >= new Date(new Date().setHours(0, 0, 0, 0))).sort((a, b) => new Date(a.start) - new Date(b.start)).slice(0, 8);
  const selectedPosts = activeStatus ? posts.filter((post) => post.status === activeStatus).sort((a, b) => new Date(a.start) - new Date(b.start)) : [];
  const byStatus = (status) => posts.filter((post) => post.status === status).length;
  return <aside className="sidebar">
    <section className={`preference-meter ${scheduleInsight ? scheduleInsight.score : 'idle'} ${scheduleInsight?.isDragging ? 'analyzing' : ''}`} aria-live="polite"><div className="meter-heading"><p>Schedule preference</p><strong>{scheduleInsight ? (scheduleInsight.isDragging ? '...' : `${scheduleInsight.preference}%`) : '--'}</strong></div><div className="meter-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow={scheduleInsight?.isDragging ? undefined : scheduleInsight?.preference || 0}><div className="meter-fill" style={{ width: `${scheduleInsight?.isDragging ? 58 : scheduleInsight?.preference || 0}%` }} /></div>{scheduleInsight ? <><div className="meter-result"><span>{scheduleInsight.label}</span><time>{scheduleInsight.isDragging ? 'Analyzing' : scheduleInsight.scheduledAt.toLocaleString([], { weekday: 'short', hour: 'numeric', minute: '2-digit' })}</time></div><p className="meter-copy">{scheduleInsight.message}</p>{!scheduleInsight.isDragging && <small>Better window: {scheduleInsight.alternative}</small>}</> : <p className="meter-copy">Drag a post to see how preferable its new time is.</p>}</section>
    <div className="sidebar-heading"><h2>Upcoming posts</h2><span className="post-count">{upcoming.length}</span></div>
    <div className="schedule-summary" aria-label="Post status summary"><button className="summary-item scheduled-action" onClick={() => setActiveStatus('draft')} aria-label="Show all draft posts"><strong>{byStatus('draft')}</strong><span>Drafts</span></button><button className="summary-item scheduled-action" onClick={() => setActiveStatus('scheduled')} aria-label="Show all scheduled posts"><strong>{byStatus('scheduled')}</strong><span>Scheduled</span></button><button className="summary-item scheduled-action" onClick={() => setActiveStatus('published')} aria-label="Show all live posts"><strong>{byStatus('published')}</strong><span>Live</span></button></div>
    {upcoming.length === 0 && <p className="empty">Nothing scheduled yet.</p>}<ul>{upcoming.map((post) => <li key={post.id}><span className="dot" style={{ backgroundColor: post.color }} /><div><div className="title">{post.title}</div><div className="meta">{post.platform} {' / '} {new Date(post.start).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</div><span className={`badge ${post.status}`}>{post.status}</span></div></li>)}</ul>
    {activeStatus && <div className="scheduled-overlay" role="presentation" onClick={() => setActiveStatus(null)}><section className="scheduled-popup" role="dialog" aria-modal="true" aria-labelledby="saved-posts-title" onClick={(event) => event.stopPropagation()}><div className="popup-heading"><div><p>Content queue</p><h2 id="saved-posts-title">{activeStatus === 'draft' ? 'Draft posts' : activeStatus === 'scheduled' ? 'Scheduled posts' : 'Live posts'}</h2></div><button onClick={() => setActiveStatus(null)} aria-label="Close saved posts">Close</button></div>{selectedPosts.length ? <ul className="scheduled-post-list">{selectedPosts.map((post) => <li key={post.id}><span className="dot" style={{ backgroundColor: post.color }} /><div><h3>{post.title}</h3><p>{post.platform} / {new Date(post.start).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>{post.notes && <blockquote>{post.notes}</blockquote>}</div></li>)}</ul> : <p className="empty">There are no {activeStatus === 'published' ? 'live' : activeStatus} posts yet.</p>}</section></div>}
  </aside>;
}
