import { useState } from "react";
import { logout, updateProfile } from "../services/authService";
function Dashboard({ session, onSession, onLogout, dark, setDark }) {
  const [tab, setTab] = useState("overview"); const [form, setForm] = useState({ name: session.user.name, email: session.user.email }); const [notice, setNotice] = useState("");
  function save(event) { event.preventDefault(); const result = updateProfile(form); if (result.error) setNotice(result.error); else { onSession(result.session); setNotice("Profile saved successfully."); } }
  function signOut() { logout(); onLogout(); }
  const initials = session.user.name.split(" ").map((word) => word[0]).join("").slice(0, 2);
  return <main className="dashboard-page"><nav className="topbar"><div className="brand"><span className="brand-mark">S</span> SecureSpace</div><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)}>{dark ? "☀" : "◐"}</button><button className="logout-button" onClick={signOut}>Sign out</button></div></nav><section className="dashboard-content"><aside className="sidebar"><div className="avatar">{initials}</div><strong>{session.user.name}</strong><small>{session.user.role}</small><button className={tab === "overview" ? "selected" : ""} onClick={() => setTab("overview")}>▦ Overview</button><button className={tab === "profile" ? "selected" : ""} onClick={() => setTab("profile")}>◉ My profile</button><button className={tab === "activity" ? "selected" : ""} onClick={() => setTab("activity")}>◷ Activity</button></aside><div className="workspace">{tab === "overview" && <><p className="eyebrow">OVERVIEW</p><h1>Welcome back, {session.user.name.split(" ")[0]}.</h1><p className="subtle">Here is a quick picture of your SecureSpace account.</p><div className="stats-grid"><article><span className="stat-icon purple">✓</span><div><small>Account status</small><strong>Active</strong></div></article><article><span className="stat-icon blue">◷</span><div><small>Saved sessions</small><strong>1 device</strong></div></article><article><span className="stat-icon green">♙</span><div><small>Access level</small><strong>{session.user.role}</strong></div></article></div><section className="chart-card"><div><p className="eyebrow">WEEKLY ACTIVITY</p><h2>Your workspace pulse</h2><p>You have stayed consistently active this week.</p></div><div className="bar-chart">{[38, 62, 44, 76, 58, 91, 67].map((value, index) => <span key={index} style={{ height: `${value}%` }} title={`${value}% activity`}></span>)}</div><div className="week"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></section></>}{tab === "profile" && <section className="profile-card"><p className="eyebrow">PROFILE SETTINGS</p><h1>Make it yours.</h1><p className="subtle">Update the details associated with your account.</p><form onSubmit={save}><label>Full name</label><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><label>Email address</label><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} />{notice && <div className="form-alert">{notice}</div>}<button className="primary-button">Save changes <span>→</span></button></form></section>}{tab === "activity" && <section className="activity-card"><p className="eyebrow">ACCOUNT ACTIVITY</p><h1>Recent activity.</h1>{session.activity.map((item, index) => <div className="activity-row" key={item}><span>✓</span><div><strong>{item}</strong><small>{index === 0 ? "Just now" : `${index * 8 + 2} minutes ago`}</small></div></div>)}</section>}</div></section></main>;
} export default Dashboard;
