import { Link, useLocation } from "react-router-dom";
import { logout, updateProfile } from "../services/authService";
import { useState } from "react";
const roleInfo = { Admin: { description: "Full system access", color: "purple" }, Editor: { description: "Can create and edit content", color: "blue" }, Viewer: { description: "Read-only access", color: "green" } };
function Dashboard({ session, onSession, onLogout, dark, setDark }) {
  const location = useLocation(); const [form, setForm] = useState({ name: session.user.name, email: session.user.email }); const [notice, setNotice] = useState(""); const role = session.user.role; const is = (path) => location.pathname === path;
  function signOut() { logout(); onLogout(); } function save(event) { event.preventDefault(); const result = updateProfile(form); setNotice(result.error || "Profile saved successfully."); if (result.session) onSession(result.session); }
  const initials = session.user.name.split(" ").map((word) => word[0]).join("").slice(0, 2);
  const links = [["/dashboard", "▦ Overview"], ["/profile", "◉ My profile"], ["/activity", "◷ Activity"], ...(role === "Admin" ? [["/admin", "⚙ Admin panel"]] : []), ...(["Admin", "Editor"].includes(role) ? [["/editor", "✎ Editor space"]] : [])];
  let page = <Overview role={role} />; if (is("/profile")) page = <section className="profile-card"><p className="eyebrow">PROFILE SETTINGS</p><h1>Make it yours.</h1><p className="subtle">Update the details associated with your account.</p><form onSubmit={save}><label>Full name</label><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><label>Email address</label><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} />{notice && <div className="success-alert">{notice}</div>}<button className="primary-button">Save changes <span>→</span></button></form></section>; if (is("/activity")) page = <Activity />; if (is("/admin")) page = <AdminPanel />; if (is("/editor")) page = <EditorPanel role={role} />;
  return <main className="dashboard-page"><nav className="topbar"><div className="brand"><span className="brand-mark">S</span> SecureSpace</div><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)}>{dark ? "☀" : "◐"}</button><button className="logout-button" onClick={signOut}>Sign out</button></div></nav><section className="dashboard-content"><aside className="sidebar"><div className="avatar">{initials}</div><strong>{session.user.name}</strong><small>{roleInfo[role].description}</small><span className={`role-badge ${roleInfo[role].color}`}>{role}</span>{links.map(([to, label]) => <Link className={is(to) ? "selected" : ""} to={to} key={to}>{label}</Link>)}</aside><div className="workspace">{page}</div></section></main>;
}
function Overview({ role }) { const info = roleInfo[role]; return <><p className="eyebrow">ROLE-BASED DASHBOARD</p><h1>Welcome back.</h1><p className="subtle">Your interface and routes adapt to your <b>{role}</b> permissions.</p><div className="stats-grid"><article><span className="stat-icon purple">✓</span><div><small>Account status</small><strong>Active</strong></div></article><article><span className={`stat-icon ${info.color}`}>♙</span><div><small>Your role</small><strong>{role}</strong></div></article><article><span className="stat-icon green">◷</span><div><small>Route access</small><strong>{role === "Admin" ? "All areas" : role === "Editor" ? "Editor areas" : "Viewer areas"}</strong></div></article></div><section className="chart-card"><p className="eyebrow">PERMISSION SUMMARY</p><h2>{info.description}</h2><p>{role === "Admin" ? "You can manage users, permissions, content, and reports." : role === "Editor" ? "You can access the editor workspace and update published content." : "You can view your dashboard, profile, and account activity."}</p></section></>; }
function Activity() { return <section className="activity-card"><p className="eyebrow">ACCOUNT ACTIVITY</p><h1>Recent activity.</h1>{["Signed in successfully", "Permissions verified", "Workspace access granted"].map((item, index) => <div className="activity-row" key={item}><span>✓</span><div><strong>{item}</strong><small>{index === 0 ? "Just now" : `${index * 8 + 2} minutes ago`}</small></div></div>)}</section>; }
function AdminPanel() { return <section className="admin-card"><p className="eyebrow">ADMIN-ONLY ROUTE</p><h1>Access control center.</h1><p className="subtle">Only Admin users can view this route and these permission controls.</p><div className="permission-table"><b>Admin</b><span>Manage users, roles, routes</span><b>Editor</b><span>Edit content and access editor space</span><b>Viewer</b><span>View permitted content only</span></div></section>; }
function EditorPanel() { return <section className="admin-card"><p className="eyebrow">EDITOR ROUTE</p><h1>Content workspace.</h1><p className="subtle">This route is available to Admin and Editor roles, but hidden from Viewers.</p><button className="primary-button">Create draft <span>→</span></button></section>; }
export default Dashboard;
